version: "3.7"

services:
  wordpress:
    container_name: mysite_wordpress
    image: leonpahole/wordpress-boilerplate
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysite_mysql
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - uploads:/var/www/html/wp-content/uploads

  db:
    container_name: mysite_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  uploads:
  db:

networks:
  default:
    external:
      name: leonpahole_com_prod_nginx
